### ISSUE TITLE
When is the code published?

### ISSUE THREAD

**Issue by ErikOrjehag** [TRI-ML/KP3D#1]
Hello, very interesting project! Is there a planned date for the code to be published?

**Comment by RaresAmbrus** [comment]
Hi, thanks for the interest! We're working on releasing code and should hopefully have something ready in the next couple of months.

**Comment by RaresAmbrus** [comment]
Thanks for the interest and patience! We added code for our models and inference to replicate our results (https://github.com/TRI-ML/KP3D/pull/6). Please let us know if you run into any issues or have any other questions about our paper.
