### ISSUE TITLE
code release ?

### ISSUE THREAD

**Issue by schenock** [TRI-ML/KP3D#3]
Hi,

when is the code getting published?

thank you!
Dane

**Comment by RaresAmbrus** [comment]
Hi, thanks for the interest! We're working on the code and should hopefully have something ready in the next couple of months.

**Comment by schenock** [comment]
Okay, thank you. looking forward to it.

**Comment by ComputerMath** [comment]
Hello, 
I'm watching whether the code update is done or not frequently nowadays. 
Is there any issue or plan about uploading the code recently?
thanks in advance :)

**Comment by RaresAmbrus** [comment]
Hi, thank you for the interest and sorry it's taking this long: we had to postpone the release due to other internal deadlines. I'm still hoping to get to this soon - I'll post an update once I make some progress. Thanks again!

**Comment by davidljung** [comment]
This paper has been listed on [paperswithoutcode.com](http://paperswithoutcode.com/) due to not being reproducible without code.

**Comment by RaresAmbrus** [comment]
Thanks for the interest and patience! We added code for our models and inference to replicate our results (https://github.com/TRI-ML/KP3D/pull/6). Please let us know if you run into any issues or have any other questions about our paper.

**Comment by ComputerMath** [comment]
thanks for opening code.
Do you have any plans to add additional any train code ?

**Comment by RaresAmbrus** [comment]
@ComputerMath - no plans to release the training code, but happy to answer any specific questions about our method.
