### ISSUE TITLE
F2F 

### ISSUE THREAD

**Issue by adizhol** [TRI-ML/KP3D#5]
Hello,
In your paper, you mention F2F in the qualitative comparison graphs. 
What paper/model does it refer to?

**Comment by RaresAmbrus** [comment]
Hi, 
The F2F method was a frame-to-frame baseline where we computed the ego-motion between 2 frames using PnP and RANSAC (based on openCV). It's not a learned method, but we use the predicted keypoints + predicted depth in the target image and matched them against the predicted keypoints in the context image.

**Comment by adizhol** [comment]
OK, thank you
